<?php

/**
 * @package     Magegeeks_Hideprice
 * @Developer   Deepak Mankotia
 * @Email       deepakmankotiacse@gmail.com
 */


?>
<?php
#condition to check user is loggedin or not
if(!Mage::getSingleton('customer/session')->isLoggedIn() AND Mage::getStoreConfig('magegeeks_hideprice/magegeeks_group/price_enable')):
    echo '<span class="login_for_price"><b>'.Mage::getStoreConfig('magegeeks_hideprice/magegeeks_group/cart_text').'</b></span><br>';
    return;
endif;
?>
<?php $_product = $this->getProduct(); ?>
<?php $buttonTitle = $this->__('Add to Cart'); ?>
<?php if($_product->isSaleable()): ?>
    <div class="add-to-cart">
        <?php if(!$_product->isGrouped()): ?>
        <label for="qty"><?php echo $this->__('Qty:') ?></label>
        <input type="text" name="qty" id="qty" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>" title="<?php echo $this->__('Qty') ?>" class="input-text qty" />
        <?php endif; ?>
        <button type="button" title="<?php echo $buttonTitle ?>" id="product-addtocart-button" class="button btn-cart" onclick="productAddToCartForm.submit(this)"><span><span><?php echo $buttonTitle ?></span></span></button>
        <?php echo $this->getChildHtml('', true, true) ?>
    </div>
<?php endif; ?>
